# Generated by Django 3.1.3 on 2020-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profession',
        ),
    ]
